networks:
  dev-network:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - my-backend
      - my-frontend
    networks:
      - dev-network

  my-backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
    - dev-network

  my-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dev-network
